#!/bin/bash


cp OUT_dbscrn_naive_$1.csv results2/OUT_dbscrn_naive_$1.csv
cp STAT_dbscrn_naive_$1.csv results2/STAT_dbscrn_naive_$1.csv
cp DEBUG_dbscrn_naive_$1.csv results2/DEBUG_dbscrn_naive_$1.csv

cp OUT_dbscrn_optim_$1.csv results2/OUT_dbscrn_optim_$1.csv
cp STAT_dbscrn_optim_$1.csv results2/STAT_dbscrn_optim_$1.csv
cp DEBUG_dbscrn_optim_$1.csv results2/DEBUG_dbscrn_optim_$1.csv